<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="XTS" Id="{74115216-9c4a-0cfc-0a38-bdb4d9dc9f35}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM XTS
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="XTS">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>